### ISSUE TITLE
Compact PDF Option

### ISSUE THREAD

**Issue by jasonlones** [ctsit/save_survey_pdf_to_field#11]
Would it be possible to add an option for being able to chose the 'compact' PDF version?  Thanks!

**Comment by pbchase** [comment]
This project is officially end-of-life. The Vanderbilt University Medical Center team incorporated the functionality of this module into REDCap 10.6.0 on 2020-11-30. They are part of the survey option “Save a PDF of completed survey response to a File Upload field”. We recommend all users of the module reconfigure their REDCap projects to use the features in REDCap core. Release 1.1.3 of this module will be the last version released. Users are welcome to fork this module for their own use, but UF CTS-IT will no longer be providing support or updates.
