### ISSUE TITLE
Feature request: Select event where PDF gets saved

### ISSUE THREAD

**Issue by steentje34** [ctsit/save_survey_pdf_to_field#12]
In the current version of the external module, for longitudinal projects, the survey PDF gets saved in the event that the survey was designated to. It would be a nice improvement if it would be possible to select the event where the survey PDF gets saved in the external module's project-level configuration.

Alternatively, it would be nice to explicitely document the current behaviour (i.e. survey PDF gets saved in the same event) in the external module's documentation.

**Comment by pbchase** [comment]
This project is officially end-of-life. The Vanderbilt University Medical Center team incorporated the functionality of this module into REDCap 10.6.0 on 2020-11-30. They are part of the survey option “Save a PDF of completed survey response to a File Upload field”. We recommend all users of the module reconfigure their REDCap projects to use the features in REDCap core. Release 1.1.3 of this module will be the last version released. Users are welcome to fork this module for their own use, but UF CTS-IT will no longer be providing support or updates.
