### ISSUE TITLE
Save survey dies quietly if not enough rights

### ISSUE THREAD

**Issue by denshade** [ctsit/save_survey_pdf_to_field#13]
When writing the pdf it should be checked if the file could be written. 
In write_pdf it says: 
  file_put_contents($full_path_to_temp_file, $pdf_content);

Expected:
The return value of file_put_contents should be checked and logged if it fails. 
Actual:
The return value is not checked and fails silently.

**Comment by pbchase** [comment]
This project is officially end-of-life. The Vanderbilt University Medical Center team incorporated the functionality of this module into REDCap 10.6.0 on 2020-11-30. They are part of the survey option “Save a PDF of completed survey response to a File Upload field”. We recommend all users of the module reconfigure their REDCap projects to use the features in REDCap core. Release 1.1.3 of this module will be the last version released. Users are welcome to fork this module for their own use, but UF CTS-IT will no longer be providing support or updates.
