### ISSUE TITLE
[BUG] Survey PDF cannot be saved to multiple locations

### ISSUE THREAD

**Issue by remifrazierucsf** [ctsit/save_survey_pdf_to_field#16]
## Is your feature request related to a problem? Please describe.
The module can be configured to save PDFs from one form into multiple fields in a project.  

Example:
![image](https://user-images.githubusercontent.com/29136540/88434549-43e3d200-cdb5-11ea-9cf7-18622eb4dcd5.png)

However, in this use case, the module currently only writes the PDF from the form to the *first* field identified, and does not write to the following fields which are meant to contain copies of the PDF.

## Describe the solution you'd like
Update the module to permit writing copies of a form's PDF to multiple locations.

## Additional context
It seems likely that processing stops after a single successful write.

**Comment by pbchase** [comment]
This project is officially end-of-life. The Vanderbilt University Medical Center team incorporated the functionality of this module into REDCap 10.6.0 on 2020-11-30. They are part of the survey option “Save a PDF of completed survey response to a File Upload field”. We recommend all users of the module reconfigure their REDCap projects to use the features in REDCap core. Release 1.1.3 of this module will be the last version released. Users are welcome to fork this module for their own use, but UF CTS-IT will no longer be providing support or updates.
