### ISSUE TITLE
Issue with blank survey being saved

### ISSUE THREAD

**Issue by NikNakk** [ctsit/save_survey_pdf_to_field#19]
I've got an odd bug where sometimes a blank copy of the survey gets saved into the field, and then the real survey cannot be uploaded and so the error email gets generated. It's only happened twice so far in the first 100 surveys on this project. The survey in question is using the eConsent module and all of the fields are required. The survey therefore should never be submitted successfully with blank fields. I'll keep trying to identify a way of reproducing this, but I've not been able to identify the precise circumstances that trigger it so far.

**Comment by NikNakk** [comment]
It looks like the hook is sometimes being called even though the survey is not complete. It seems like a fix would be to check  whether the survey is marked as complete prior to saving the PDF. If I have time, I'll have a look at implementing this.

**Comment by pbchase** [comment]
This project is officially end-of-life. The Vanderbilt University Medical Center team incorporated the functionality of this module into REDCap 10.6.0 on 2020-11-30. They are part of the survey option “Save a PDF of completed survey response to a File Upload field”. We recommend all users of the module reconfigure their REDCap projects to use the features in REDCap core. Release 1.1.3 of this module will be the last version released. Users are welcome to fork this module for their own use, but UF CTS-IT will no longer be providing support or updates.
