### ISSUE TITLE
Longitudinal form get saved in the 2nd event on events 2-n

### ISSUE THREAD

**Issue by pbchase** [ctsit/save_survey_pdf_to_field#9]
This module works in longitudinal projects, but it has an odd behavior.  When saving a form on any event but the first, the form is saved in the _second_ file upload field. We tested in this in 2nd, 3rd, and 4th events. It's unclear why this happens.  A project XML file is attached to expedite testing. 

[TestSaveSurveyPDFToF_2018-08-14_1502.REDCap.xml.txt](https://github.com/ctsit/save_survey_pdf_to_field/files/2288163/TestSaveSurveyPDFToF_2018-08-14_1502.REDCap.xml.txt)

**Comment by tbembersimeao** [comment]
@pbchase check commit https://github.com/ctsit/save_survey_pdf_to_field/pull/10/commits/706fa0c90a57dac3c4284e30f679ad3015b96ac1.

The event ID was being wrongly passed to the function that verifies whether the field is already populated. It was causing false positives on that function (when fields from other events were populated).

PR #10 fixes that + adds a few adjustments.
